language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: "mVFS4V9RJQIj/dK4TL70B6vw0glzaomTtW7qJWQd93jQ8IPHjTEOhkQmv4JlFx+EW6QXmxvpJw3V4C4ENWgehXRheTLQ9+5Mnk6Yk9MZPz3H6STGTI7q3tpFC2DZxypM4MzbcGLxVldg1sZG6dlGtgnvwKQqWJUX3vuaWJJSPHzAI2lcs0nY2zYs69tr4B15A9I27Fx1omuVuyovcMepqDbFdiTKRxfluBXaJG2H/ERNjQEGn/7rOi45oJbH9EhK3AQaeM5srFwCG809K/zMq+rNdpvB5e2PL2r15XVdDVw93ODZ41H0w/KI0Sf5930dy3wLvOsxuy9jkanEbTygl5emhxncG62ZqJJh89+SvhQ7ra0TB7W45X0J/0RPelkv0fiQvRNbUchAWLg3A9uRAQFQU4uirOiH8fyrmJ6SCOTlSmP/vk0qWFk0TbWVl4GMrnMNz5PU1VQnpmDqUMQdL2gbyD9TIVky2oAuW95kXcPhXsejFuMaWVHXRedBhk0nBryu+hDZMi7VP8fJph1sNzz+W1EojOieiQqJZIrTCebvwpm2zqUI1hWEOOsbifAo7Q23fp5ayd4KwX4kT6d2Y7a9+C8aBR+i+ibRcoU402qX+UBx4eTsv88mtlfX21+umLSD7td61qm3ZrM+fiJFgwt7crH/3LTvikrlbHi1XOg="
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- travis_wait 40 conda build ./recipe -c csdms-stack -c defaults -c conda-forge --old-build-string
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-
  fi
